# Generated by Django 5.1.4 on 2024-12-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_created=True, verbose_name="Время создания"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите наименование",
                        max_length=100,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Завод", "Завод"),
                            ("Розничная сеть", "Розничная сеть"),
                            (
                                "Индивидуальный предприниматель",
                                "Индивидуальный предприниматель",
                            ),
                        ],
                        default="Индивидуальный предприниматель",
                        help_text="Выберете тип предприятия",
                        max_length=30,
                        verbose_name="Тип предприятия",
                    ),
                ),
                ("level", models.SmallIntegerField(default=0, verbose_name="уровень")),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
    ]
