# Generated by Django 5.1.4 on 2024-12-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0005_remove_supplier_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="city",
            field=models.CharField(
                blank=True, help_text="Введите Город", null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="country",
            field=models.CharField(
                default=1, help_text="Введите страну", verbose_name="Страна"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="debts",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Введите сумму задолженности",
                max_digits=20,
                null=True,
                verbose_name="Задолженность перед поставщиком",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                default=1,
                help_text="Введите e-mail",
                max_length=254,
                verbose_name="Email",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="supplier",
            name="level",
            field=models.SmallIntegerField(default=0, verbose_name="уровень"),
        ),
        migrations.AddField(
            model_name="supplier",
            name="parent_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="Выберете поставщика",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="suppliers.supplier",
                verbose_name="Поставщик",
            ),
        ),
        migrations.AddField(
            model_name="supplier",
            name="street",
            field=models.CharField(
                blank=True, help_text="Введите улицу", null=True, verbose_name="Улица"
            ),
        ),
    ]
