# Generated by Django 5.1.4 on 2024-12-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0006_supplier_city_supplier_country_supplier_debts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="type",
        ),
        migrations.AlterField(
            model_name="supplier",
            name="country",
            field=models.CharField(
                default="Россия", help_text="Введите страну", verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="level",
            field=models.IntegerField(
                choices=[
                    (0, "завод"),
                    (1, "розничная сеть"),
                    (2, "индивидуальный предприниматель"),
                ],
                default=0,
                verbose_name="Уровень сети",
            ),
        ),
    ]
