# Generated by Django 5.1.4 on 2024-12-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0007_remove_supplier_type_alter_supplier_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="create_time",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Время создания"
            ),
        ),
    ]
