# Generated by Django 5.1.4 on 2024-12-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(
                default=1,
                help_text="Введите наименование",
                max_length=100,
                verbose_name="Наименование",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="release_date",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату релиза",
                null=True,
                verbose_name="дата релиза продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="Укажите модель",
                max_length=100,
                null=True,
                verbose_name="Укажите модель",
            ),
        ),
    ]
